name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_and_test:
    strategy:
      matrix:
        runs-on: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build with gradle
        uses: gradle/gradle-build-action@v3
      - name: build and test
        run: |
          ./gradlew clean build test packageUberJarForCurrentOS packageDistributionForCurrentOS
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-data-${{ matrix.runs-on }}
          path: |
            dlt-filter-app/build/compose/jars/dlt-filter*
            dlt-filter-app/build/compose/binaries/**/*.deb
            dlt-filter-app/build/compose/binaries/**/*.msi
