name: release build
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_releases:
    strategy:
      matrix:
        runs-on: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    name: Create release on ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build with gradle
        uses: gradle/gradle-build-action@v3
      - name: build and test
        run: |
          ./gradlew build 
          ./gradlew jar 
          ./gradlew packageDistributionForCurrentOS
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        id: artifacts
        with:
          name: artifacts_installer_${{ matrix.runs-on }}
          path: |
            dlt-filter-app/build/compose/binaries/main/**/*.deb
            dlt-filter-app/build/compose/binaries/main/**/*.msi

  release:
    needs: [create_releases]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: retrieve artifacts
        uses: actions/download-artifact@v4
        with:
          path: distribution
          merge-multiple: true
      - run: ls -lR distribution
      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |-
            distribution/deb/*.deb
            distribution/msi/*.msi
